### ISSUE TITLE
unable to connected 

### ISSUE THREAD

**Issue by charybdeBE** [waliens/jdrhelper-java-client#2]
salut quand  je lance le fichier jar et que j'entre mes identifiants j'ai un message d'erreur dans ma console windows

évr. 13, 2017 6:36:23 PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.101 by JavaFX runtime of version 8.0.45
fÚvr. 13, 2017 6:36:30 PM be.rmormont.jdrhelper.client.ApplicationContext$2 onFailure
AVERTISSEMENT: Connection failure for user 'Charybde'
fÚvr. 13, 2017 6:36:30 PM be.rmormont.jdrhelper.client.rest.BaseCallback onFailure
GRAVE: Response to 'POST https://www.jdrhelper.com/api-token-auth' not received. Cause: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
fÚvr. 13, 2017 6:36:34 PM be.rmormont.jdrhelper.client.ApplicationContext$2 onFailure
AVERTISSEMENT: Connection failure for user 'Charybde'
fÚvr. 13, 2017 6:36:34 PM be.rmormont.jdrhelper.client.rest.BaseCallback onFailure
GRAVE: Response to 'POST https://www.jdrhelper.com/api-token-auth' not received. Cause: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
fÚvr. 13, 2017 6:37:01 PM be.rmormont.jdrhelper.client.ApplicationContext$2 onFailure
AVERTISSEMENT: Connection failure for user 'Charybde'
fÚvr. 13, 2017 6:37:01 PM be.rmormont.jdrhelper.client.rest.BaseCallback onFailure
GRAVE: Response to 'POST https://www.jdrhelper.com/api-token-auth' not received. Cause: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Et sur l'ui ju'ai just : an error occured" 

Pareil avec le .exe

**Comment by waliens** [comment]
Essaye un peu ça ? http://stackoverflow.com/a/36464452
